### ISSUE TITLE
请教下，有统计过分类分支的acc吗，和单独的分类器模型比效果如何

### ISSUE THREAD

**Issue by connorchen** [Duankaiwen/CPNDet#15]
这种把分类器嵌入进去进行端到端训练，和单独训练一个分类器，他们的分类精度有多大差别呢。
我现在用的是 anchor-free模型+独立分类器模型 来解决误报问题的，想尝试下你这种端到端训练的方法，请多指教

**Comment by Duankaiwen** [comment]
@connorchen 你好，单独训练一个分类器是指怎样训练？能说的具体一些么
