### ISSUE TITLE
CUDA out of memory.

### ISSUE THREAD

**Issue by Ostyk** [Duankaiwen/CPNDet#17]
Hi, 

I came here following your suggestion to use this instead of CenterNet. I actually managed to train CenterNet with promising results but decided to try this out since the code base is very similar, and has more promising inference speed.

So the setup is almost exactly the same (compiling custom layers etc) but I'm heaving trouble with CUDA out of memory errors, 12% into the training which seems bizarre to me. 

Env setup:
using the same instance as for training Centernet which worked fine.
- 4 x  Tesla V100-SXM2 (16GB RAM), CUDA 10.1

I setup the config file of **HG52** with various chunk sizes (even batch size 4, 1 image per gpu) and the same error persists.
Attaching the log below.

I will be very grateful for any advice that you might have.

LOG:
iter 1165, all: 4.9353, focal: 3.4306, grouping:0.8367, region: 0.5174, regr: 0.1507
iter 1170, all: 5.6282, focal: 3.9427, grouping:0.9505, region: 0.5869, regr: 0.1482
iter 1175, all: 5.3373, focal: 3.7071, grouping:0.8346, region: 0.6310, regr: 0.1647
iter 1180, all: 5.3797, focal: 3.7966, grouping:0.8720, region: 0.5691, regr: 0.1419
 12%|████▎                               | 1184/10000 [42:00<5:12:45,  2.13s/it]
Traceback (most recent call last):
  File "train.py", line 203, in <module>
    train(training_dbs, validation_db, args.start_iter)
  File "train.py", line 143, in train
    training_loss, focal_loss, grouping_loss, region_loss,regr_loss = nnet.train(**training)
  File "/home/ubuntu/CPNDet/code/nnet/py_factory.py", line 97, in train
    loss.backward()
  File "/home/ubuntu/CenterNet/env/lib/python3.6/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/ubuntu/CenterNet/env/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: CUDA out of memory. Tried to allocate 3.86 GiB (GPU 0; 15.75 GiB total capacity; 10.16 GiB already allocated; 3.86 GiB free; 554.53 MiB cached)

**Comment by Ostyk** [comment]
Ok, managed to solve it through having a significantly smaller batch size that would take up only 10/16gb on average

**Comment by wuyinq** [comment]
> Ok, managed to solve it through having a significantly smaller batch size that would take up only 10/16gb on average

Except smaller batch-size,  do you have any other ideas?  Thanks!
