### ISSUE TITLE
RuntimeError: cuda runtime error (98) : invalid device function at CPNDet-master/codes/models/py_utils/roi_extractors/ops/roi_align/src/roi_align_kernel.cu:139

### ISSUE THREAD

**Issue by ulanbator** [Duankaiwen/CPNDet#21]
Someone encountered such a problem？

**Comment by Ostyk** [comment]
Yeah, I did while testing on edge devices it. It's due to a memory issue. I tried hardcoding the num_threads in the c++ files but that didnt seem to work at all. Solved it partially but using a smaller test scale.

**Comment by ulanbator** [comment]
thanks
