### ISSUE TITLE
huawei cloud :ModuleNotFoundError: No module named 'moxing'how can I solve it?

### ISSUE THREAD

**Issue by HongrenWang** [Duankaiwen/CPNDet#9]

**Comment by Duankaiwen** [comment]
where is the error？

**Comment by HongrenWang** [comment]
谢谢我已经解决了,您在华为云上有mox调用,已经修改完成了.

**Comment by ashley-mv** [comment]
Remove these two lines 
-import moxing as mox
-mox.file.shift('os', 'mox')

 Remove -with file.File(self._cache_file, "wb") as f 
Add: **with open(self._cache_file, "wb") as f**
